### ISSUE TITLE
Doubt about API 

### ISSUE THREAD

**Issue by roishub** [Arjun-Siva/typing-trials#11]
How to set Environment variable for- REACT_APP_ARENA_CREATE_API and other APIs used.
Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON this is the error that i got.

**Comment by Arjun-Siva** [comment]
@roishub Setup the backend server first. Then create `.env` file in frontend folder. Inside that declare the environment variables.
For local environment you can set up something like - 

`
REACT_APP_PARAGRAPH_API=http://localhost:4000/api/paragraph
REACT_APP_LOGIN_API=http://localhost:4000/api/user/login
REACT_APP_SIGNUP_API=http://localhost:4000/api/user/signup
REACT_APP_SCORES_API=http://localhost:4000/api/scores
REACT_APP_ARENA_JOIN_API=http://localhost:4000/api/arena/join
REACT_APP_ARENA_CREATE_API=http://localhost:4000/api/arena/create
REACT_APP_SOCKET_API=http://localhost:4000
`

**Comment by Arjun-Siva** [comment]
@roishub For backend, create a mongodb database in mongodb atlas and you can use it. similar to frontend store them in a .env file
```
PORT=4000
MONGO_URI=mongodb+srv://<your-url>
SECRET=<your-secret>
DATABASE=<your-database>
PARA_API=http://metaphorpsum.com/paragraphs/2
```

For random text I fetched it from this website
